export const FETCH_LIST_ITEM_REQUEST = 'FETCH_LIST_ITEM_REQUEST';
export const FETCH_LIST_ITEM_SUCCESS = 'FETCH_LIST_ITEM_SUCCESS';
export const FETCH_LIST_ITEM_FAILURE = 'FETCH_LIST_ITEM_FAILURE';

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';

export const DELETE_LIST_ITEM_REQUEST = 'DELETE_LIST_ITEM_REQUEST';
export const DELETE_LIST_ITEM_SUCCESS = 'DELETE_LIST_ITEM_SUCCESS';
export const DELETE_LIST_ITEM_FAILURE = 'DELETE_LIST_ITEM_FAILURE';

export const CHANGE_ITEM_FIELD = 'CHANGE_ITEM_FIELD';
export const CANCEL_CHANGE_ITEM = 'CANCEL_CHANGE_ITEM';

export const SAVE_CHANGE_ITEM_REQUEST = 'SAVE_CHANGE_ITEM_REQUEST';
export const SAVE_CHANGE_ITEM_SUCCESS = 'SAVE_CHANGE_ITEM_SUCCESS';
export const SAVE_CHANGE_ITEM_FAILURE = 'SAVE_CHANGE_ITEM_FAILURE';